# Generated by Django 5.1 on 2024-09-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(max_length=45)),
                ('cover', models.ImageField(upload_to='portifolio/covers/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=45)),
                ('positions', models.CharField(max_length=45)),
                ('initialized_at', models.DateField()),
                ('finished_at', models.DateField()),
                ('reponsabilities', models.TextField()),
                ('visible', models.BooleanField(verbose_name=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=45)),
                ('academic_title', models.CharField(max_length=45)),
                ('course', models.CharField(max_length=45)),
                ('initialized_at', models.DateField()),
                ('finished_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('descrption_contact', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Complementary_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('instituition', models.CharField(max_length=45)),
                ('duration', models.IntegerField()),
                ('mounth', models.CharField(max_length=45)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=45)),
                ('number', models.CharField(max_length=45)),
                ('neighborhood', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=45)),
                ('zipcode', models.CharField(max_length=45)),
                ('complement', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=45)),
                ('icon', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField()),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
    ]
