# Generated by Django 4.0 on 2024-11-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_alter_interests_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='file',
            field=models.FileField(null=True, upload_to='portifolio/cover/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='education',
            name='final_project_theme',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('personal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.personal')),
            ],
        ),
    ]
