# Generated by Django 4.0 on 2024-11-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_education_file_education_final_project_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='icon',
        ),
        migrations.AddField(
            model_name='skills',
            name='visible_icon',
            field=models.BooleanField(null=True, verbose_name=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='file',
            field=models.FileField(null=True, upload_to='portifolio/covers/%Y/%m/%d/'),
        ),
    ]
