# Generated by Django 4.0 on 2024-11-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0008_message_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_published',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
