# Generated by Django 4.0 on 2024-11-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0009_alter_message_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
